### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by monkxy** [ElementalH/Blooket-hacks#1]
These scripts are all stolen from my repo, take these down now or i will DMCA you.

**Comment by ElementalH** [comment]
Done, sorry, I didn't take time to read the license since it is 201 lines long. But I'll read it someday, tho, can I put your code, and give credit?

**Comment by ElementalH** [comment]
Done, sorry, I didn't know it was yours, a friend of mine name crazycat on github gave me it, I thought it was original

**Comment by ElementalH** [comment]
I'm new to java script, he said I could use it until I master (get better) at javascript coding

**Comment by ElementalH** [comment]
oh and apologies for annoying you, but I have a question, where did you learn javascript coding? If it's a website, could you send the URL for me?

**Comment by ElementalH** [comment]
thanks
